### ISSUE TITLE
Evasion techniques

### ISSUE THREAD

**Issue by Kikobeats** [microlinkhq/browserless#11]
**Libraries**

- https://github.com/paulirish/headless-cat-n-mouse
- https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-stealth

**URLs to test**

- [x] https://www.stuff.co.nz/national/politics/108051628/poll-shows-labour-overtake-national
- [x] https://www.zomato.com/bangalore/bold-marathahalli
- [x] https://www.reddit.com/r/news/comments/8vebjp/lebron_james_takes_154_million_4year_deal_with/?st=JJ41AUKB&sh=be6868cb
- [x] https://www.reddit.com/r/funny/comments/8ltsck/this_sea_dog_is_the_ultimate_prankster/
- [ ] https://www.zillow.com/homedetails/4611-Cardinal-Ridge-Way-Flowery-Branch-GA-30542/83350172_zpid
- [ ] https://www.kmart.com.au/product/portable-charger-15000mah/2168305
- [ ] https://www.bloomberg.com/news/articles/2019-01-15/here-are-five-volatility-charts-keeping-wall-street-up-at-night?srnd=premium-canada
- [ ] https://www.scmp.com/week-asia/opinion/article/2112486/inconvenient-truths-murder-journalism-india
- [ ] https://startse.com/noticia/netflix-do-esporte-planeja-chegada-ao-brasil-ma-noticia-para-globo
- [ ] https://www.coches.net/segunda-mano/
- [ ] https://www.ouest-france.fr/
- [ ] https://www.washingtonpost.com/nation/2020/06/25/coronavirus-live-updates-us/

**Comment by captainjackrana** [comment]
@Kikobeats has this been included as part of browserless now? Or do we need to explicitly do all the evasions mentioned there?

**Comment by Kikobeats** [comment]
browserless doesn't have (yet) evasion technique; It has a [adblock](https://github.com/Kikobeats/browserless/issues/26) and using it is enough for most of cases

**Comment by captainjackrana** [comment]
Any plans of including these evasions in browserless in the near future?

**Comment by Kikobeats** [comment]
Eventually yes, but not sure if this will be a significant addition since most of tested urls are already reachables.


Can you explain what are you doing? 🙂

I want to use `puppeteer-extra-plugin-stealth` but t is coupled to `puppeteer-extra` as framework.

**Comment by captainjackrana** [comment]
@Kikobeats It should be fairly easy to integrate the stealth plugin as well. I tried it out in my local application by making some changes in the `packages/browserless/index.js`

`puppeteer = requireOneOf(['puppeteer-extra', 'puppeteer', 'puppeteer-core', 'puppeteer-firefox']),
  incognito = false,
  timeout = 30000,
  ...launchOpts
} = {}) => {
  if(launchOpts.stealthMode && puppeteer.constructor.name === 'PuppeteerExtra'){
    puppeteer.use((require('puppeteer-extra-plugin-stealth')()));
  }`

This seems to pass all the headless tests here - https://intoli.com/blog/not-possible-to-block-chrome-headless/chrome-headless-test.html

I can submit a PR for this if needed. Would be a wonderful addition

**Comment by Kikobeats** [comment]
Yes please, make a PR 🙂

why `puppeteer.constructor.name === 'PuppeteerExtra'` is necessary?

**Comment by captainjackrana** [comment]
Well, the `puppeteer.use` method is only available for the `puppeteer-extra` package. So, its just an additional safety check in case people use the `stealthMode` option, without having the package installed. 

On second thought, its better to remove that, so that it actually throws an error in case that flag is used inappropriately

**Comment by Granitosaurus** [comment]
I see that the stealth PR has been closed - is stealth implementation available right now or is it WIP?

**Comment by Kikobeats** [comment]
@Granitosaurus not yet, that's why the issue is still open

**Comment by eherrerosj** [comment]
Why was this merged and then the issue was reopened @Kikobeats? Also, could you kindly explain to me how could this technique be used through the browserless api? Maybe through the [function](https://docs.browserless.io/docs/function.html) endpoint?

**Comment by Kikobeats** [comment]
@eherrerosj this repository does not relate with browserless.io service

To see they on action see: https://browserless.js.org/#/?id=evasions

If you use [Microlink API](https://api.microlink.io], they are enabled by default.
