### ISSUE TITLE
[goto] Disable JavaScript

### ISSUE THREAD

**Issue by Timkor** [microlinkhq/browserless#123]
When rendering PDF's server side it's often better to disable JavaScript execution. It just uses unnecessary server resources while it's most of the time not necessary to render the page.

It would be awesome if we could pass a property to `/pdf` where we can disable JavaScript in:
https://github.com/microlinkhq/browserless/blob/master/packages/pdf/src/index.js

Puppeteer supports this out of the box if you just use `page.setJavaScriptEnabled(false)` before navigation to a page:
https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#pagesetjavascriptenabledenabled

**Comment by Kikobeats** [comment]
Thanks for the suggestion!

This could be a thing to add at `goto` level, very similar to `disableAnimations`
https://github.com/microlinkhq/browserless/blob/master/packages/goto/src/index.js#L97

Then, when you need to make a PDF, you can pass this option with the rest of the options, like https://github.com/microlinkhq/browserless#options-3

Can you make a PR? 🙂

**Comment by Timkor** [comment]
Thank you for your feedback. I made a pull request:
https://github.com/microlinkhq/browserless/pull/124

Do you think this will work out of the box as it is?

**Comment by Kikobeats** [comment]
Released at v5.19.9 🙂

**Comment by Timkor** [comment]
@Kikobeats You are a hero. Cheers
