### ISSUE TITLE
goto: Rename `disableAnimations` into `animations`

### ISSUE THREAD

**Issue by Kikobeats** [microlinkhq/browserless#127]

**Comment by adityawankhede5** [comment]
I have found in total 13 exact matches for disableAnimations: 
**So should I rename all the matches or only those present /packages/goto/ directory.**

1. CHANGELOG.md:294:* ensure to call disableAnimations after goto ([d73c964](https://github.com/kikobeats/browserless/commit/d73c9643c7c3253f90fbb5bcdcb86ee369b75c19))
1. packages/browserless/src/index.js:99:    html: evaluate(page => page.content(), { disableAnimations: false }),
1. packages/browserless/src/index.js:104:      disableAnimations: false
1. packages/goto/CHANGELOG.md:129:* ensure to call disableAnimations after goto ([d73c964](https://github.com/kikobeats/browserless/tree/master/packages/goto/commit/d73c9643c7c3253f90fbb5bcdcb86ee369b75c19))
1. packages/goto/src/index.js:59:    { url, media, adblock = true, headers = {}, waitFor = 0, disableAnimations = true, disableJavaScript = false, 
...args }
1. packages/goto/src/index.js:101:      if (disableAnimations) {
1. packages/goto/src/index.js:102:        debug({ disableAnimations })
1. README.md:137:  disableAnimations: false
1. README.md:163:  disableAnimations: false
1. README.md:189:  disableAnimations: true,
1. README.md:260:  disableAnimations: true,
1. README.md:466:    disableAnimations: false
1. README.md:510:##### disableAnimations

**Comment by Kikobeats** [comment]
Just matches inside goto package:
https://github.com/microlinkhq/browserless/blob/master/packages/goto/src/index.js#L65
