### ISSUE TITLE
browserless not using proxy server

### ISSUE THREAD

**Issue by justserp** [microlinkhq/browserless#259]
### Prerequisites

- ["browserless": "^8.7.11" ] I'm using the last version.
- [ ] My node version is the same as declared as `package.json`.

### browserless not using proxy server 

despite passing the proxy server details in the args, browserless doesnt launch puppeteer with my proxy server. I have tested the proxy server independently with with puppeteer and puppeteer-extra. so the issue isnt the proxy server 

### Steps to reproduce

```js
import puppeteer from 'puppeteer-extra'
import StealthPlugin from 'puppeteer-extra-plugin-stealth'
import browserles from 'browserless'

puppeteer.use(StealthPlugin())
const browserless = browserles()

(async function () {
    try {
        let pageHtml = await browserless.html('https://httpbin.org/ip', {
            puppeteer:puppeteer,
            args:[`--proxy-server=${'my-proxy-deatils'}`,'--disable-gpu', '--single-process', '--no-zygote', '--no-sandbox', '--hide-scrollbars'],
            incognito: true
        })
        console.log(pageHtml)
    } catch(e){ 
        throw new Error(e.message)
    }
})()
```

### Expected behaviour
ip address be the IP address of my proxy server

### Actual behaviour
shows ip of my machine instead

**Comment by Kikobeats** [comment]
Hello,

the proxy details are not properly passed on your code.

Try with this:

```js
const browserless = browserles({
  proxy: 'myproxy'
})
```

In case you want to pass flags arguments to chromium, you need to follow the same `puppeteer` interface for that:

```js
const browserless = browserles({
  proxy: 'myproxy',
  args: [
  '--disable-gpu', 
  '--single-process',
  '--no-zygote', 
  '--no-sandbox', 
  '--hide-scrollbars'
  ]
})
```

reference: https://github.com/microlinkhq/browserless/blob/master/packages/browserless/src/index.js#L22
