### ISSUE TITLE
Lighthouse: images for desktop reports returning mobile interface

### ISSUE THREAD

**Issue by dustinsgoodman** [microlinkhq/browserless#312]
## Bug Report

**Current Behavior**
When I use the following MQL API, the report returns the `result.data.insights.lighthouse.audits['final-screenshot']` is returned as a base64 encoded image. However, this image is of the mobile view and not of the desktop view of the website.

```
const url = 'https://anywebsitehere.com';
const payload = {
  meta: false,
  insights: {
    lighthouse: {
      device: 'desktop',
      onlyCategories: ['performance', 'best-practices', 'accessibility', 'seo'],
    },
    technologies: false,
  },
};

const result = await mql(url, payload);
```

**Expected behavior/code**

I'd expect the above to return the desktop variation of the image and not a mobile version.

**Additional context/Screenshots**

Can be provided upon request.

**Comment by Kikobeats** [comment]
Thanks for reporting!

What is happening there is it's necessary to add some ergonomic to load `presets` as the same way they are loaded using Lighthouse CLI

https://github.com/GoogleChrome/lighthouse/blob/15c430093caa6249ef8552ed910b9d3663aa48fd/lighthouse-cli/bin.js#L83

Let me do it 🙂

**Comment by Kikobeats** [comment]
@dustinsgoodman added a new `preset´ field inside the lighthouse configuration to easily load a bunch of lighthouse settings.

demo: https://runkit.com/kikobeats/6154e9aa0106dd000832f6c0

Can you confirm to me it's working fine for you?

**Comment by Kikobeats** [comment]
Microlink documentation is now reflecting that:

https://microlink.io/docs/api/parameters/insights/lighthouse

**Comment by dustinsgoodman** [comment]
Awesome! My team will test on Monday and send you any feedback. Amazing turnaround on this btw!

**Comment by dustinsgoodman** [comment]
Just coming back to say this was a great fix and works fantastic! Thank you!

**Comment by Kikobeats** [comment]
Thanks to you for reporting!
