### ISSUE TITLE
Problem with screenshot.

### ISSUE THREAD

**Issue by julioflima** [microlinkhq/browserless#332]
### Prerequisites

- [x] I'm using the last version.
- [x] My node version is the same as declared as `package.json`.

### Subject of the issue

I couldn't try it.

### Steps to reproduce

const browserless = require("browserless");

const saveBufferToFile = (buffer, fileName) => {
  const wstream = require("fs").createWriteStream(fileName);
  wstream.write(buffer);
  wstream.end();
};

browserless
  .screenshot("https://bot.sannysoft.com", { device: "iPhone 6" })
  .then((buffer) => {
    const fileName = "screenshot.png";
    saveBufferToFile(buffer, fileName);
    console.log(`your screenshot is here: `, fileName);
  });

### Expected behaviour

Save a screenshot.

### Actual behaviour

$ node index.js
/home/juliolima/projects/poc_browserless/index.js:10
  .screenshot("https://bot.sannysoft.com", { device: "iPhone 6" })
   ^

TypeError: browserless.screenshot is not a function
    at Object.<anonymous> (/home/juliolima/projects/poc_browserless/index.js:10:4)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
error Command failed with exit code 1.

**Comment by Kikobeats** [comment]
Hello,

Check the README file. You should create a browserless instance before interacting with the screenshot method.

Alternatively, you can just call Microlink API:
https://api.microlink.io/?url=https://bot.sannysoft.com&screenshot&meta=false&embed=screenshot.url&device=iphone6
