### ISSUE TITLE
Add types

### ISSUE THREAD

**Issue by spa5k** [microlinkhq/browserless#334]
### Prerequisites

- [x] I'm using the last version.
- [x] My node version is the same as declared as `package.json`.

### Subject of the issue

When you import the browserless on a typescript based project, the error is given that it has no types, i also don't see them in the repo or in @types.

### Steps to reproduce

Just create a new typescript project and import the browserless.
```ts
import createBrowserless from 'browserless';
```
Tell us how to reproduce this issue.

### Expected behaviour

Browserless should have types, so that it can be used easily in typescript and help the user with intellisense.

### Actual behaviour
It has no inbuilt types or no info on them being installed separately.

**Comment by spa5k** [comment]
To be fair, if you want, i can start porting some of the packages to their typescript counterpart.

**Comment by Kikobeats** [comment]
The library doesn't have types; really appreciated if you can make a PR adding them 🙏

**Comment by spa5k** [comment]
https://github.com/airbnb/ts-migrate/tree/master/packages/ts-migrate 

Have you tried using it? The lerna config is a bit confusing and it is erroring for no reason while installing.

**Comment by Kikobeats** [comment]
I don't want to rewrite all the code to TypeScript; just add types over the public interfaces
