### ISSUE TITLE
'Technical Details' section missing (?)

### ISSUE THREAD

**Issue by d4h0** [microlinkhq/browserless#421]
Hi,

it seems, the 'Technical Details' section is missing.

The README and https://browserless.js.org/ contain the following paragraph:

> You can read more about that at [technical details](https://browserless.js.org/#/) section.

But the link doesn't lead anywhere.

I'm interested in learning what `browserless` does, so I might apply the same to Playwright.

**Comment by Kikobeats** [comment]
Thanks for reporting!

I'm not sure what was linked there, so I just removed it.
