### ISSUE TITLE
BrowserlessError: EBRWSRTIMEOUT, Promise timed out after 30000 milliseconds

### ISSUE THREAD

**Issue by theMoe** [microlinkhq/browserless#450]
How can I change the timeout?

**Comment by Kikobeats** [comment]
Hello, see https://browserless.js.org/#/?id=initializing-a-browser 🙂

**Comment by theMoe** [comment]
Hi, thanks! If I run my code on a local MacBook, the code works fine without any issues. But if I run the same code on a Ubuntu VPS I get this timeout error. Any idea to solve it?

**Comment by Kikobeats** [comment]
Probably the VPS machine resources needs to be higher. 

Try with a dedicated CPU with at least 2 CPUs and 4GB of memory.

**Comment by theMoe** [comment]
Okay, its not a dedicated CPU but if I run the code on ubuntu with e.g. npm run start, it works fine.

If I run it as systemctl service, the code takes way longer or runs into a timeout.
